### ISSUE TITLE
Error: Requires Babel "^7.0.0-beta.41", but was loaded with "7.9.0"

### ISSUE THREAD

**Issue by mnpenner** [codemod-js/codemod#598]
I'm getting this error:

```
❯ codemod --plugin @babel/plugin-proposal-function-bind src/resources/assets/scripts
Error: Requires Babel "^7.0.0-beta.41", but was loaded with "7.9.0". You'll need to update your @babel/core version.
```

I suspect this is a quirk of npm global bins trying to use local packages (why on earth it would try to do that, I don't know), but maybe you should upgrade codemod out of babel 7 beta?

---

Or maybe it's not codemod that has this dependency...? Here's the rest of the stack:

```
    at throwVersionError (/path/to/my/project/node_modules/@babel/helper-plugin-utils/lib/index.js:63:11)
    at Object.assertVersion (/path/to/my/project/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at /path/to/my/project/node_modules/@babel/plugin-proposal-function-bind/lib/index.js:17:7
    at /path/to/my/project/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at new Plugin (/path/to/my/project/node_modules/@codemod/cli/src/Config.ts:23:22)
    at Config.<anonymous> (/path/to/my/project/node_modules/@codemod/cli/src/Config.ts:82:18)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/my/project/node_modules/@codemod/cli/src/Config.js:5:58)
```

I don't know who wants what :(

---

FWIW, it does the same thing if I run everything locally:

```
node_modules/.bin/codemod --find-babel-config --plugin node_modules/@babel/plugin-proposal-function-bind/lib/index.js src/r
esources/assets/scripts
Error: Requires Babel "^7.0.0-beta.41", but was loaded with "7.9.0". You'll need to update your @babel/core version.
```

**Comment by protoEvangelion** [comment]
I'm getting the same error code when running: `codemod --plugin babel-plugin-transform-commonjs file.js` from every @codemod/cli version on npm: `2.1.2 - 2.1.15`.

@eventualbuddha any suggestions?

**Comment by josiah-roberts** [comment]
Also encountering this issue.

**Comment by eventualbuddha** [comment]
Have you tried `@codemod/cli` v2.1.16?

**Comment by eventualbuddha** [comment]
I think this is likely fixed. Closing, but let me know if you still see it.
